import { getPublicKeyAsync, signAsync } from "@noble/ed25519";

const STORAGE_KEY = "flop.did.v1";
const SESSION_DID_KEY = "flop.did.session.v1";
let activeIdentity: DidIdentity | null = null;
const ED25519_PKCS8_PREFIX = new Uint8Array([0x30, 0x2e, 0x02, 0x01, 0x00, 0x30, 0x05, 0x06, 0x03, 0x2b, 0x65, 0x70, 0x04, 0x22, 0x04, 0x20]);

function bytesToBase64Url(bytes: Uint8Array) { let binary = ""; bytes.forEach((byte) => { binary += String.fromCharCode(byte); }); return btoa(binary).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/g, ""); }
function base64UrlToBytes(value: string) { const padded = value.replace(/-/g, "+").replace(/_/g, "/") + "===".slice((value.length + 3) % 4); const binary = atob(padded); return Uint8Array.from(binary, (char) => char.charCodeAt(0)); }
function concat(...parts: Uint8Array[]) { const result = new Uint8Array(parts.reduce((sum, part) => sum + part.length, 0)); let offset = 0; for (const part of parts) { result.set(part, offset); offset += part.length; } return result; }
function base58(bytes: Uint8Array) { const alphabet = "123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz"; let digits = [0]; bytes.forEach((byte) => { let carry = byte; for (let i = 0; i < digits.length; i++) { const value = digits[i] * 256 + carry; digits[i] = value % 58; carry = Math.floor(value / 58); } while (carry) { digits.push(carry % 58); carry = Math.floor(carry / 58); } }); let output = ""; for (let i = 0; i < bytes.length && bytes[i] === 0; i++) output += "1"; for (let i = digits.length - 1; i >= 0; i--) output += alphabet[digits[i]]; return output; }
function didFromPublicBytes(bytes: Uint8Array) { return `did:key:z${base58(concat(new Uint8Array([0xed, 0x01]), bytes))}`; }
function didFromPublicKey(x: string) { return didFromPublicBytes(base64UrlToBytes(x)); }

export type DidIdentity = { did: string; jwk: JsonWebKey };
export function didFromJwk(jwk: JsonWebKey) { if (jwk.kty !== "OKP" || jwk.crv !== "Ed25519" || !jwk.x) throw new Error("Expected an Ed25519 JWK containing x and d"); return didFromPublicKey(jwk.x); }
async function identityFromSeed(seed: Uint8Array): Promise<DidIdentity> { if (seed.length !== 32) throw new Error("Ed25519 seed must be 32 bytes"); const publicKey = await getPublicKeyAsync(seed); const x = bytesToBase64Url(publicKey); return { did: didFromPublicBytes(publicKey), jwk: { kty: "OKP", crv: "Ed25519", x, d: bytesToBase64Url(seed) } }; }
export async function generateIdentity(): Promise<DidIdentity> { return identityFromSeed(crypto.getRandomValues(new Uint8Array(32))); }
export function parseImportedJwk(raw: string): DidIdentity { const jwk = JSON.parse(raw) as JsonWebKey; if (!jwk.d) throw new Error("Private JWK must contain d"); return { did: didFromJwk(jwk), jwk }; }
export async function parseSeed(seedText: string): Promise<DidIdentity> { const value = seedText.trim().replace(/\s/g, ""); if (!/^[0-9a-fA-F]{64}$/.test(value)) throw new Error("Seed must be exactly 64 hexadecimal characters."); const seed = Uint8Array.from(value.match(/../g)!.map((byte) => parseInt(byte, 16))); return identityFromSeed(seed); }
export async function parseImportedPem(raw: string): Promise<DidIdentity> { const match = raw.match(/-----BEGIN ([A-Z0-9 ]*PRIVATE KEY)-----([\s\S]+?)-----END \1-----/); const rawSeed = raw.trim(); if (!match && /^[0-9a-fA-F]{64}$/.test(rawSeed)) return parseSeed(rawSeed); if (!match) throw new Error("Unsupported identity.pem. Choose an Ed25519 PEM private key or a 64-character Ed25519 seed file."); const binary = atob(match[2].replace(/\s/g, "")); const decoded = Uint8Array.from(binary, (char) => char.charCodeAt(0)); if (decoded.length === 32) return identityFromSeed(decoded); if (decoded.length === 64) return identityFromSeed(decoded.slice(0, 32)); if (decoded.length >= 48 && decoded.slice(0, 16).every((byte, index) => byte === ED25519_PKCS8_PREFIX[index])) return identityFromSeed(decoded.slice(16, 48)); throw new Error("The selected PEM is not a supported Ed25519 private key. It must contain PKCS#8 Ed25519 or a raw 32-byte seed."); }
export async function didFromPublicKeyFile(raw: string): Promise<string> { const value = raw.trim(); if (isValidDid(value)) return value; const pem = value.match(/-----BEGIN PUBLIC KEY-----([\s\S]+?)-----END PUBLIC KEY-----/); if (pem) { const binary = atob(pem[1].replace(/\s/g, "")); const der = Uint8Array.from(binary, (char) => char.charCodeAt(0)); if (der.length < 32) throw new Error("Invalid Ed25519 public key file"); return didFromPublicBytes(der.slice(-32)); } const parts = value.split(/\s+/); if (parts[0] === "ssh-ed25519" && parts[1]) { const binary = atob(parts[1].replace(/-/g, "+").replace(/_/g, "/") + "===".slice((parts[1].length + 3) % 4)); const bytes = Uint8Array.from(binary, (char) => char.charCodeAt(0)); const read32 = (offset: number) => new DataView(bytes.buffer, bytes.byteOffset + offset, 4).getUint32(0); const typeLength = read32(0); const keyLengthOffset = 4 + typeLength; const keyLength = read32(keyLengthOffset); const keyStart = keyLengthOffset + 4; if (typeLength !== 11 || keyLength !== 32 || bytes.length < keyStart + keyLength) throw new Error("Invalid ssh-ed25519 key.pub file"); return didFromPublicBytes(bytes.slice(keyStart, keyStart + keyLength)); } throw new Error("Unsupported key.pub. Use an OpenSSH ssh-ed25519 public key or PEM PUBLIC KEY file."); }
export async function signIdentity(identity: DidIdentity, message: string) { if (!identity.jwk.d) throw new Error("A private Ed25519 key is required for signing"); const signature = await signAsync(new TextEncoder().encode(message), base64UrlToBytes(identity.jwk.d)); return bytesToBase64Url(signature); }
export function setActiveIdentity(identity: DidIdentity | null) { activeIdentity = identity; }
export function getActiveIdentity() { return activeIdentity; }
export function nextNonce(did: string, room: string) { const key = `flop.nonce.v1.${did}.${room}`; const previous = Number(localStorage.getItem(key) || "0"); const next = Math.max(Date.now(), previous + 1); localStorage.setItem(key, String(next)); return String(next); }

async function deriveKey(password: string, salt: Uint8Array) { return crypto.subtle.deriveKey({ name: "PBKDF2", salt: salt as unknown as BufferSource, iterations: 250_000, hash: "SHA-256" }, await crypto.subtle.importKey("raw", new TextEncoder().encode(password), "PBKDF2", false, ["deriveKey"]), { name: "AES-GCM", length: 256 }, false, ["encrypt", "decrypt"]); }
export async function saveIdentity(identity: DidIdentity, password: string) { if (password.length < 8) throw new Error("Use at least 8 characters for the local encryption password"); const salt = crypto.getRandomValues(new Uint8Array(16)); const iv = crypto.getRandomValues(new Uint8Array(12)); const key = await deriveKey(password, salt); const ciphertext = await crypto.subtle.encrypt({ name: "AES-GCM", iv }, key, new TextEncoder().encode(JSON.stringify(identity.jwk))); localStorage.setItem(STORAGE_KEY, JSON.stringify({ salt: bytesToBase64Url(salt), iv: bytesToBase64Url(iv), data: bytesToBase64Url(new Uint8Array(ciphertext)) })); }
export async function loadIdentity(password: string): Promise<DidIdentity> { const stored = localStorage.getItem(STORAGE_KEY); if (!stored) throw new Error("No saved Digital ID found in this browser"); const value = JSON.parse(stored); const key = await deriveKey(password, base64UrlToBytes(value.salt)); const plain = await crypto.subtle.decrypt({ name: "AES-GCM", iv: base64UrlToBytes(value.iv) }, key, base64UrlToBytes(value.data)); const jwk = JSON.parse(new TextDecoder().decode(plain)) as JsonWebKey; return { did: didFromJwk(jwk), jwk }; }
export function clearIdentity() { localStorage.removeItem(STORAGE_KEY); }
export function hasSavedIdentity() { return Boolean(localStorage.getItem(STORAGE_KEY)); }
export function isValidDid(value: string) { return /^did:key:z[1-9A-HJ-NP-Za-km-z]{47}$/.test(value); }
export function setSessionDid(did: string | null) { if (did) sessionStorage.setItem(SESSION_DID_KEY, did); else sessionStorage.removeItem(SESSION_DID_KEY); }
export function getSessionDid() { return sessionStorage.getItem(SESSION_DID_KEY) ?? ""; }
export const DID_STORAGE_KEY = STORAGE_KEY;
