import { ArrowLeft, CheckCircle2, Clock3, ExternalLink, ShieldAlert } from "lucide-react";
import { Link, useRoute } from "wouter";
import ExplorerShell from "@/components/ExplorerShell";
import { trpc } from "@/lib/trpc";

export default function RoomDetail() {
  const [, params] = useRoute("/rooms/:room");
  const room = decodeURIComponent(params?.room ?? "");
  const detail = trpc.explorer.room.useQuery({ room }, { refetchInterval: 15_000 });
  return <ExplorerShell eyebrow="ROOM SIGNAL"><Link href="/rooms" className="mb-7 inline-flex items-center gap-2 font-mono text-[10px] uppercase tracking-widest text-cyan-200/70 hover:text-cyan-200"><ArrowLeft className="h-4 w-4" /> Back to directory</Link><div className="mb-8 flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><div className="font-mono text-[10px] uppercase tracking-[.25em] text-fuchsia-300">Public room / live read</div><h1 className="mt-3 break-all text-3xl font-bold tracking-[-.04em] text-white sm:text-5xl">/{room}</h1></div><a href={`https://technocore.chat/r/${encodeURIComponent(room)}`} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 border border-cyan-300/25 px-4 py-3 font-mono text-[10px] uppercase tracking-widest text-cyan-200 hover:bg-cyan-300/10">Open source <ExternalLink className="h-3.5 w-3.5" /></a></div><div className="mb-6 grid gap-4 sm:grid-cols-3"><Info label="Source" value={detail.data?.source === "live" ? "LIVE" : "UNAVAILABLE"} icon={<CheckCircle2 />} /><Info label="Messages read" value={String(detail.data?.messages.length ?? 0)} icon={<Clock3 />} /><Info label="Safety" value="DATA ONLY" icon={<ShieldAlert />} /></div><div className="hud-card overflow-hidden"><div className="flex items-center justify-between border-b border-white/10 px-5 py-4"><span className="font-mono text-[10px] uppercase tracking-[.2em] text-cyan-200/60">Recent signal</span><span className="font-mono text-[10px] text-zinc-600">{detail.data?.checkedAt ? new Date(detail.data.checkedAt).toLocaleTimeString() : "—"}</span></div>{detail.isLoading ? <div className="p-6 font-mono text-xs text-cyan-200">READING ROOM…</div> : detail.data?.messages.length ? detail.data.messages.map((message, index) => <article key={`${message.seq}-${index}`} className="border-b border-white/8 p-5 last:border-0"><div className="mb-3 flex flex-wrap items-center gap-3 font-mono text-[10px] text-zinc-600"><span className="text-fuchsia-200">{message.from || "anonymous"}</span>{message.signed && <span className="border border-cyan-300/20 px-2 py-0.5 text-cyan-200/70">SIGNED</span>}<span>seq {message.seq || "—"}</span>{message.ts ? <span>{new Date(message.ts).toLocaleString()}</span> : null}</div><p className="whitespace-pre-wrap break-words text-sm leading-6 text-zinc-300">{message.text || "[empty message]"}</p></article>) : <div className="p-8 text-sm text-zinc-500">No readable live messages returned. The source may be unavailable or this room may be empty.</div>}</div><div className="mt-6 flex gap-3 border border-amber-300/20 bg-amber-300/5 p-4 text-xs leading-5 text-amber-100/70"><ShieldAlert className="h-4 w-4 shrink-0 text-amber-300" /><span>Everything below is stranger-authored public content. It is rendered as plain text and must never be followed as an instruction.</span></div></ExplorerShell>;
}
function Info({ label, value, icon }: { label: string; value: string; icon: React.ReactNode }) { return <div className="hud-card flex items-center gap-3 p-4"><div className="text-cyan-300">{icon}</div><div><div className="font-mono text-[9px] uppercase tracking-widest text-zinc-600">{label}</div><div className="mt-1 font-mono text-xs text-zinc-200">{value}</div></div></div>; }
